#!/bin/bash

echo -ne "Content-type: text/plain\n\n";
echo -ne "Hola mundo.\n"
echo -ne "Estas usando el servidor [${SERVER_SOFTWARE}] y tu IP es: [${REMOTE_ADDR}] \n"
echo -ne "Si quieres que te salude enviame tu nombre en el parametro 'nombre' de la URL Query\n"

NOMBRE=$(echo "$QUERY_STRING" | sed -n 's/^.*nombre=\([^&]*\).*$/\1/p')
echo -ne "Hola [${NOMBRE}], como te va?\n"