#!/bin/bash

NOMBRE=$(echo "$QUERY_STRING" | sed -n 's/^.*nombre=\([^&]*\).*$/\1/p')
if [[ "${NOMBRE}" == "" ]]; then
    NOMBRE="desconocido"
fi

echo -ne "Content-type: text/html\n\n";
echo -ne "<!DOCTYPE html>\n"
echo -ne "<html lang='en'>\n"
echo -ne "<head>\n"
echo -ne "    <meta charset='UTF-8'>\n"
echo -ne "    <meta name='viewport' content='width=device-width, initial-scale=1.0'>\n"
echo -ne "    <title>Document</title>\n"
echo -ne "</head>\n"
echo -ne "<body>\n"
echo -ne "  <h1>Hola mundo y hola persona</h1>\n"
echo -ne "  <p>A las buenas tardes, que sepas que estás usando el servidor <code>[${SERVER_SOFTWARE}]</code> y tu IP es: <code>[${REMOTE_ADDR}]</code> </p>\n"
echo -ne "  <p>Si quieres que te salude enviame tu nombre en el parametro  <code>nombre</code> de la URL Query </p>\n"
echo -ne "  <p>Hola <strong>${NOMBRE}</strong>, ¿como te va?\n"
echo -ne "</body>\n"
echo -ne "</html>\n"
